In [50]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import Imputer

In [51]:
%pwd

'/Users/marcrivera/Downloads/open-university-learning-analytics-dataset'

In [52]:
dfstudentinfo = pd.read_csv("studentInfo.csv")
dfstudentasses = pd.read_csv("studentAssessment.csv")
dfvle = pd.read_csv("vle.csv")
dfstudentvle = pd.read_csv("studentVle.csv")
dfstudentreg = pd.read_csv ("studentRegistration.csv")
dfcourses = pd.read_csv ("courses.csv")
dfasses = pd.read_csv ("assessments.csv")

In [53]:
dfstudentasses.isnull().sum()

id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64

In [54]:
dfvle.isnull().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [55]:
dfstudentvle.isnull().sum()

code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64

In [56]:
dfstudentreg.isnull().sum()

code_module                0
code_presentation          0
id_student                 0
date_registration         45
date_unregistration    22521
dtype: int64

In [57]:
dfasses.isnull().sum()

code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64

In [58]:
dfcourses.isnull().sum()

code_module                   0
code_presentation             0
module_presentation_length    0
dtype: int64

In [59]:
dfstudentinfo.isnull().sum()

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

In [60]:
#finding the rows with null values in imd_band column
dfstudentinfo[dfstudentinfo['imd_band'].isnull()]

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
9,AAA,2013J,53025,M,North Region,Post Graduate Qualification,NaN,55<=,0,60,N,Pass
17,AAA,2013J,71361,M,Ireland,HE Qualification,NaN,35-55,0,60,N,Pass
28,AAA,2013J,104476,M,Ireland,Post Graduate Qualification,NaN,35-55,0,60,N,Pass
34,AAA,2013J,114017,F,North Region,Post Graduate Qualification,NaN,35-55,0,60,N,Pass
65,AAA,2013J,172112,M,Ireland,HE Qualification,NaN,35-55,0,60,N,Pass
66,AAA,2013J,172797,F,Ireland,A Level or Equivalent,NaN,35-55,0,60,N,Pass
68,AAA,2013J,175392,M,North Region,HE Qualification,NaN,35-55,0,60,N,Pass
88,AAA,2013J,227517,M,Ireland,HE Qualification,NaN,0-35,0,180,N,Fail
180,AAA,2013J,376439,M,North Region,HE Qualification,NaN,0-35,0,60,N,Distinction
184,AAA,2013J,386924,M,Ireland,Lower Than A Level,NaN,0-35,0,120,N,Pass
223,AAA,2013J,603861,M,North Region,HE Qualification,NaN,55<=,0,60,N,Withdrawn
258,AAA,2013J,1801229,M,Ireland,HE Qualification,NaN,35-55,0,60,N,Pass
304,AAA,2013J,2358056,F,North Region,HE Qualification,NaN,0-35,0,60,N,Fail
339,AAA,2013J,2550279,F,North Region,HE Qualification,NaN,35-55,0,60,N,Pass
349,AAA,2013J,2574528,M,Ireland,HE Qualification,NaN,35-55,0,60,N,Pass
470,AAA,2014J,263952,M,North Region,Lower Than A Level,NaN,35-55,0,60,N,Distinction
527,AAA,2014J,345519,F,North Region,A Level or Equivalent,NaN,0-35,0,60,N,Pass
542,AAA,2014J,375260,M,Ireland,HE Qualification,NaN,0-35,0,60,N,Pass
564,AAA,2014J,402204,M,West Midlands Region,A Level or Equivalent,NaN,35-55,0,60,N,Pass
578,AAA,2014J,429858,M,Ireland,Lower Than A Level,NaN,0-35,0,300,N,Distinction
619,AAA,2014J,603861,M,North Region,HE Qualification,NaN,55<=,1,60,N,Withdrawn
634,AAA,2014J,684180,M,North Region,HE Qualification,NaN,0-35,0,120,N,Pass
636,AAA,2014J,696073,F,Ireland,Lower Than A Level,NaN,0-35,0,60,N,Pass
819,BBB,2013B,152910,M,West Midlands Region,A Level or Equivalent,NaN,0-35,0,60,N,Pass
983,BBB,2013B,352364,F,South Region,A Level or Equivalent,NaN,35-55,0,60,N,Distinction
1141,BBB,2013B,438379,F,Ireland,Lower Than A Level,NaN,35-55,2,210,N,Withdrawn
1165,BBB,2013B,446045,F,South Region,Lower Than A Level,NaN,35-55,0,60,N,Pass
1345,BBB,2013B,500815,F,Ireland,A Level or Equivalent,NaN,0-35,0,60,N,Pass
1348,BBB,2013B,500958,M,North Region,Lower Than A Level,NaN,0-35,1,180,N,Pass
1598,BBB,2013B,532839,F,North Region,HE Qualification,NaN,0-35,0,60,N,Withdrawn
...,...,...,...,...,...,...,...,...,...,...,...,...
29661,FFF,2014J,689827,F,Ireland,A Level or Equivalent,NaN,0-35,0,60,N,Withdrawn
29722,FFF,2014J,693236,M,North Region,HE Qualification,NaN,0-35,0,120,N,Pass
29724,FFF,2014J,693345,F,Ireland,HE Qualification,NaN,0-35,0,150,N,Pass
29728,FFF,2014J,693519,M,North Region,HE Qualification,NaN,0-35,0,90,N,Pass
29740,FFF,2014J,694128,M,North Region,Lower Than A Level,NaN,0-35,0,90,N,Pass
29741,FFF,2014J,694144,M,North Region,A Level or Equivalent,NaN,35-55,0,60,N,Distinction
29755,FFF,2014J,694827,M,North Region,HE Qualification,NaN,0-35,0,60,N,Pass
29760,FFF,2014J,695220,M,North Region,Lower Than A Level,NaN,35-55,0,180,Y,Withdrawn
29762,FFF,2014J,695251,M,Ireland,HE Qualification,NaN,0-35,0,60,N,Withdrawn
29766,FFF,2014J,695449,M,North Region,HE Qualification,NaN,35-55,0,120,N,Withdrawn
29771,FFF,2014J,695637,M,North Region,A Level or Equivalent,NaN,35-55,0,120,N,Distinction
29786,FFF,2014J,696082,M,South Region,A Level or Equivalent,NaN,0-35,0,60,N,Pass
29788,FFF,2014J,696188,M,North Region,Lower Than A Level,NaN,0-35,0,120,N,Pass
29790,FFF,2014J,696275,M,Ireland,Lower Than A Level,NaN,35-55,0,60,N,Distinction
29791,FFF,2014J,696276,M,Ireland,HE Qualification,NaN,0-35,0,60,N,Withdrawn
29860,FFF,2014J,1449171,M,Scotland,HE Qualification,NaN,35-55,0,60,N,Withdrawn
29882,FFF,2014J,1752994,M,North Region,A Level or Equivalent,NaN,35-55,0,60,Y,Pass
29907,FFF,2014J,1948159,F,North Region,A Level or Equivalent,NaN,35-55,1,60,N,Distinction
29926,FFF,2014J,2081123,M,West Midlands Region,A Level or Equivalent,NaN,0-35,0,60,N,Pass
29932,FFF,2014J,2107747,M,North Region,HE Qualification,NaN,55<=,0,60,N,Withdrawn
29988,FFF,2014J,2457440,M,West Midlands Region,A Level or Equivalent,NaN,35-55,0,60,N,Pass
30014,FFF,2014J,2546315,F,North Region,A Level or Equivalent,NaN,35-55,0,150,N,Distinction
30039,FFF,2014J,2643829,M,North Region,Lower Than A Level,NaN,0-35,0,60,N,Fail
30064,GGG,2013J,62975,M,South Region,Lower Than A Level,NaN,35-55,0,30,N,Fail
30432,GGG,2013J,584195,M,North Region,Lower Than A Level,NaN,0-35,0,30,N,Pass
30552,GGG,2013J,589914,M,North Region,Lower Than A Level,NaN,0-35,0,30,N,Pass
31170,GGG,2014B,575199,F,North Western Region,Lower Than A Level,NaN,0-35,0,30,N,Pass
31389,GGG,2014B,617889,F,South West Region,Lower Than A Level,NaN,0-35,0,30,N,Fail
31777,GGG,2014B,634470,F,South Region,A Level or Equivalent,NaN,0-35,0,30,N,Distinction
32397,GGG,2014J,683974,F,North Region,Lower Than A Level,NaN,0-35,0,30,N,Distinction

In [61]:
#Dropping the rows with Null Values in 'imd_band' column should we decided to do so
dfstudentinfo.dropna(subset = ['imd_band'],how = 'all').shape

(31482, 12)

In [62]:
#new data frame df2 with no null values in imd_band column
df2 = dfstudentinfo.dropna(subset = ['imd_band'],how = 'all')

In [63]:
df2.head()

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

In [64]:
#checking for null values in d2
df2.isnull().sum()

code_module             0
code_presentation       0
id_student              0
gender                  0
region                  0
highest_education       0
imd_band                0
age_band                0
num_of_prev_attempts    0
studied_credits         0
disability              0
final_result            0
dtype: int64

In [65]:
df2.shape

(31482, 12)

In [ ]:
#creates and saves new csv to the same folder where the current notebook is running from
df2.to_csv('studentinfo2.csv')

In [42]:
#cols = dfstudentinfo(imd_band)

In [66]:
dfstudentinfo.fillna(dfstudentinfo.mode().iloc[0])

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass
5,AAA,2013J,38053,M,Wales,A Level or Equivalent,80-90%,35-55,0,60,N,Pass
6,AAA,2013J,45462,M,Scotland,HE Qualification,30-40%,0-35,0,60,N,Pass
7,AAA,2013J,45642,F,North Western Region,A Level or Equivalent,90-100%,0-35,0,120,N,Pass
8,AAA,2013J,52130,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,90,N,Pass
9,AAA,2013J,53025,M,North Region,Post Graduate Qualification,20-30%,55<=,0,60,N,Pass
10,AAA,2013J,57506,M,South Region,Lower Than A Level,70-80%,35-55,0,60,N,Pass
11,AAA,2013J,58873,F,East Anglian Region,A Level or Equivalent,20-30%,0-35,0,60,N,Pass
12,AAA,2013J,59185,M,East Anglian Region,Lower Than A Level,60-70%,35-55,0,60,N,Pass
13,AAA,2013J,62155,F,North Western Region,HE Qualification,50-60%,0-35,0,60,N,Pass
14,AAA,2013J,63400,M,Scotland,Lower Than A Level,40-50%,35-55,0,60,N,Pass
15,AAA,2013J,65002,F,East Anglian Region,A Level or Equivalent,70-80%,0-35,0,60,N,Withdrawn
16,AAA,2013J,70464,F,West Midlands Region,A Level or Equivalent,60-70%,35-55,0,60,N,Pass
17,AAA,2013J,71361,M,Ireland,HE Qualification,20-30%,35-55,0,60,N,Pass
18,AAA,2013J,74372,M,East Anglian Region,A Level or Equivalent,10-20,35-55,0,150,N,Fail
19,AAA,2013J,75091,M,South West Region,A Level or Equivalent,30-40%,35-55,0,60,N,Pass
20,AAA,2013J,77367,M,East Midlands Region,A Level or Equivalent,30-40%,0-35,0,60,N,Pass
21,AAA,2013J,91265,M,North Western Region,HE Qualification,0-10%,0-35,0,60,N,Pass
22,AAA,2013J,94961,M,South Region,Lower Than A Level,70-80%,35-55,0,60,N,Withdrawn
23,AAA,2013J,98094,M,Wales,Lower Than A Level,70-80%,35-55,0,60,N,Pass
24,AAA,2013J,100893,M,Yorkshire Region,A Level or Equivalent,20-30%,0-35,0,60,N,Pass
25,AAA,2013J,101781,M,South Region,Lower Than A Level,80-90%,35-55,0,60,N,Pass
26,AAA,2013J,102806,M,North Western Region,A Level or Equivalent,30-40%,0-35,0,60,N,Pass
27,AAA,2013J,102952,M,London Region,HE Qualification,60-70%,0-35,0,60,N,Pass
28,AAA,2013J,104476,M,Ireland,Post Graduate Qualification,20-30%,35-55,0,60,N,Pass
29,AAA,2013J,106247,M,South Region,HE Qualification,80-90%,35-55,0,60,N,Withdrawn
...,...,...,...,...,...,...,...,...,...,...,...,...
32563,GGG,2014J,1950911,F,South West Region,Lower Than A Level,40-50%,35-55,0,30,N,Pass
32564,GGG,2014J,1977701,F,South Region,Lower Than A Level,50-60%,35-55,0,30,N,Pass
32565,GGG,2014J,2004143,F,East Anglian Region,Lower Than A Level,50-60%,0-35,0,30,N,Pass
32566,GGG,2014J,2052942,F,Scotland,Lower Than A Level,50-60%,35-55,0,30,N,Pass
32567,GGG,2014J,2053521,F,South West Region,A Level or Equivalent,20-30%,35-55,1,30,Y,Pass
32568,GGG,2014J,2203216,F,Wales,A Level or Equivalent,80-90%,35-55,0,30,N,Withdrawn
32569,GGG,2014J,2214722,F,Scotland,A Level or Equivalent,70-80%,35-55,0,30,N,Withdrawn
32570,GGG,2014J,2239862,M,North Western Region,Lower Than A Level,50-60%,35-55,0,30,N,Withdrawn
32571,GGG,2014J,2268380,F,Scotland,Lower Than A Level,20-30%,35-55,0,30,N,Pass
32572,GGG,2014J,2270562,F,South East Region,Lower Than A Level,60-70%,35-55,0,30,N,Distinction
32573,GGG,2014J,2271766,F,London Region,A Level or Equivalent,30-40%,35-55,0,30,N,Pass
32574,GGG,2014J,2282141,M,Wales,A Level or Equivalent,0-10%,35-55,0,60,N,Withdrawn
32575,GGG,2014J,2311714,F,London Region,Lower Than A Level,30-40%,35-55,0,30,N,Pass
32576,GGG,2014J,2338614,F,Scotland,A Level or Equivalent,0-10%,35-55,0,30,Y,Withdrawn
32577,GGG,2014J,2342238,M,Ireland,HE Qualification,80-90%,0-35,0,30,N,Withdrawn
32578,GGG,2014J,2357806,F,Ireland,Lower Than A Level,40-50%,35-55,0,30,N,Withdrawn
32579,GGG,2014J,2373245,M,East Midlands Region,Lower Than A Level,20-30%,35-55,0,30,N,Distinction
32580,GGG,2014J,2378591,F,West Midlands Region,A Level or Equivalent,30-40%,35-55,1,30,N,Fail
32581,GGG,2014J,2456431,F,South Region,Lower Than A Level,70-80%,0-35,0,30,Y,Fail
32582,GGG,2014J,2475886,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,90,N,Fail
32583,GGG,2014J,2508153,F,East Midlands Region,Lower Than A Level,10-20,0-35,0,30,N,Pass
32584,GGG,2014J,2533195,F,South East Region,Lower Than A Level,10-20,0-35,0,30,N,Pass
32585,GGG,2014J,2606765,F,London Region,Lower Than A Level,80-90%,0-35,0,30,N,Pass
32586,GGG,2014J,2608143,M,East Midlands Region,HE Qualification,60-70%,35-55,0,30,N,Withdrawn
32587,GGG,2014J,2620947,F,Scotland,A Level or Equivalent,80-90%,0-35,0,30,Y,Distinction
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,N,Fail
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,N,Distinction
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,Y,Pass
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,N,Withdrawn
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,N,Distinction

In [67]:
dfstudentinfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
code_module             32593 non-null object
code_presentation       32593 non-null object
id_student              32593 non-null int64
gender                  32593 non-null object
region                  32593 non-null object
highest_education       32593 non-null object
imd_band                31482 non-null object
age_band                32593 non-null object
num_of_prev_attempts    32593 non-null int64
studied_credits         32593 non-null int64
disability              32593 non-null object
final_result            32593 non-null object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB

In [68]:
df3 = dfstudentinfo.fillna(dfstudentinfo.mode().iloc[0])

In [69]:
df3.isnull().sum()

code_module             0
code_presentation       0
id_student              0
gender                  0
region                  0
highest_education       0
imd_band                0
age_band                0
num_of_prev_attempts    0
studied_credits         0
disability              0
final_result            0
dtype: int64